sudo: required

language: go

go:
  - 1.3

env:
  global: # following instructions from https://github.com/cbandy/travis-oracle
  - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  - ORACLE_SID=XE
  - ORACLE_INSTANTCLIENT_FILE=oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
  - ORACLE_INSTANTCLIENT_SDK_FILE=oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
  - PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR:$PKG_CONFIG_PATH"
  - LD_LIBRARY_PATH="/usr/lib/oracle/12.1/client64/lib:$LD_LIBRARY_PATH"
  - LD_RUN_PATH="/usr/lib/oracle/12.1/client64/lib:$LD_RUN_PATH"
  - secure: wTZ4F7Q50ieai1BCPnxbrz9ccLNAN5xmbOuDuzz/Lroz+Dktc3yxsYv+oKKlkhtk/xvdR7xAKciMlHSDWTenEtVre6m3OGi4JFMtSbAUkHD3FF51vr7xFPDzaiCwMY5lQAJ2gOvgIPqDtJv2eG2L1bipNbWsiXSyWjPMG14ex+mtO5gJwHoxS4aIPceuohkhkU7+S7gbDkiF75PJ6aN7UR/7HITld/Nlkt35eyfNtSHNGflPAgiV2XBUIAj+HSPyelX/OuGXvULB8zhNlQhyXDqwEXxIH4hThTAgaGCvQqNANxYX36o8gajuCUp2vaEVSSH7Og34ADAFsVQksk0NubuuFALLzCzsymleIcFzu/+wMfkwsvQ9t2drQmk9xFv3mfPwj3z5lR7smQT3TR8/wf8HiqsIw5+bzpIggdRoc6x07i7u9zHP245EHfuTuyuQPaWofJ83+x4AWdxdGmuZSLy4JhZ09buIVs7hwxtNT6IORLu+9KQWvN/V/0vEaooh3J8glWKFFm88obRs1pWaRoKRRSs+qml1J/gs3TsjqyiqUZvsEvN31VY4M7Ise5qriAiD1QH7cVQ1R3U2tE1A+5k1WAqiMYqplArPGQQbsoi0TdUSHNbnTKfYNZ9AE7hYATbzn7xPGke1LLcgl9jTrI3TTGJO1W0cVZyvPDAUY48=
  - secure: aFdUsTvO/bzqNvUoLgAvxgDtTuYHRbxA6nhNY2fN9RQoAoSdy+5jkpUflTG4QAvu0UAbk67MDwaLVrkg2SP/n6+oCRPxAzW0QwKf3CZg0Y0nYxfUt/D+4dJ0X6/iBLZiVlEmhS0PBR2EFEXdLMzx7gOzBpyyckLsxAZPNMpMPK7dS00UoGwJssRSNBjgkMrryuQcYYNtOdPNGv1G7/+J2gqH+LXPHwDrGPUgK0j6Soco1L61DBs6u0NEyWtjqvhEkgaClUxg5SH+aYRJ2OG3etohw8O700I8iBafgTVHp8wLGtA8vkDDNhJtHlshTgupymsPsXJaWAiNuUppBhB8iVpYNZ2GLDWwccW7cHxMsAE9/LJDrkctVC9YiqIgMk9O8p/XU1lmeazRYj+ghz8MlujDwwFKheUjZrqlUKVWEk7NQDDSqSQ6hqQ4ctNHjQmKEB/MzCLxsM7TafvJjQUSPyEfwv1vHpM6v+y4G8dwzqP9i6DRweNCPAMM1cXHnJTDDtgJmfRK+RILIiCpRyz+zHyS5oiDRZxX4D2xkcHZTX9MBkIdjKX/LGnnMehvy/WdJhft1sVhjFCIRh5Yfnb7/hw04GyH78hzFRAGvvOAhfrD0J71W0SgzphE/UHind20dOlXQI87EE+5FEaS9eCdjSpAX9gLk0xUnalExU3MeNY=

before_install:
  - ".travis/oracle/download.sh"
  - ".travis/oracle/install.sh"
  - ".travis/oracle-instantclient/download_instantclient.sh"
  - ".travis/oracle-instantclient/install_instantclient.sh"